services:
  db:
    image: postgres:18.1-alpine3.23
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - db_network
    restart: always

  dash_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dash_app
    environment:
      DATABASE_URL: ${DATABASE_URL}
      APP_ENV: ${APP_ENV}
      DASH_DEBUG: ${DASH_DEBUG}
    ports:
      - "8050:8050"
    networks:
      - db_network
    restart: always
    volumes:
      - ./src:/code/src
    depends_on:
      - db

volumes:
  db_data:
    name: ${DB_NAME}_data

networks:
  db_network:
    driver: bridge
