services:
  postgres:
    image: postgres:17.5-alpine3.21
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mysecurepassword
      POSTGRES_DB: database
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - postgres_network
    restart: always

  dash_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dash_app
    ports:
      - "8050:8050"
    networks:
      - postgres_network
    restart: always
    volumes:
    - ./src:/code/src
    depends_on:
      - postgres

volumes: 
  postgres_data:
    name: postgres_data

networks:
  postgres_network:
    driver: bridge
